/* generated by extract_pulse.py — allowlisted data only */
window.AIAI_PULSE = {
 "schema": "aiai-pulse v1 \u2014 allowlisted numbers, timestamps, fixed labels only",
 "generated": "2026-06-11T16:45:03",
 "generated_day": "Thursday",
 "fields": {
  "brief": {
   "date": "2026-06-11",
   "overnight_emails": 0,
   "pending_actions": 9,
   "critical_items": 2,
   "active_research": 5
  },
  "recap": {
   "date": "2026-06-10",
   "emails_processed": 2,
   "critical": 0,
   "action_items": 0,
   "info_low": 2,
   "wins_logged": 7
  },
  "health": {
   "date": "2026-06-11",
   "checks_green": 9,
   "checks_amber": 3,
   "checks_red": 0
  },
  "filed_last_7_days": {
   "luna-evening-recap": {
    "count": 3,
    "times": [
     "Mon 21:08",
     "Tue 21:01",
     "Wed 21:01"
    ]
   },
   "luna-health-check": {
    "count": 4,
    "times": [
     "Mon 09:02",
     "Tue 09:16",
     "Wed 09:01",
     "Thu 09:07"
    ]
   },
   "luna-morning-brief": {
    "count": 4,
    "times": [
     "Mon 07:01",
     "Tue 13:35",
     "Wed 07:00",
     "Thu 07:01"
    ]
   },
   "neo-platform-radar": {
    "count": 1,
    "times": [
     "Mon 03:03"
    ]
   },
   "neo-youtube-digest": {
    "count": 2,
    "times": [
     "Tue 09:24",
     "Thu 09:08"
    ]
   },
   "neo-youtube-weekly": {
    "count": 1,
    "times": [
     "Mon 10:05"
    ]
   },
   "openclaw-news": {
    "count": 4,
    "times": [
     "Mon 06:03",
     "Tue 06:05",
     "Wed 06:02",
     "Thu 06:02"
    ]
   }
  },
  "reports_by_day": {
   "Mon": 6,
   "Tue": 5,
   "Wed": 4,
   "Thu": 4,
   "Fri": 0,
   "Sat": 0,
   "Sun": 0
  },
  "reports_this_week": 19
 }
};
